spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:sqlserver://{{DB_DEV_HOST}};databaseName={{DB_DEV_NAME}};encrypt=false;trustServerCertificate=true
    username: ${DB_DEV_USER}
    password: ${DB_DEV_PASS}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update   # auto-create tables locally if missing

  sql:
    init:
      mode: never        # disable schema.sql, rely on Hibernate/Liquibase