spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:sqlserver://${DB_LOCAL_HOST:localhost}:1433;databaseName=${DB_LOCAL_NAME:outlay-eh-service-db};encrypt=false;trustServerCertificate=true
    username: ${DB_LOCAL_USER:outlayeh_user}
    password: ${DB_DEV_PASSWORD:password!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver